const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const gamesList = [
  { gameId: 1, gameName: "Dragon’s Dogma 2" },
  { gameId: 2, gameName: "Black Myth: Wukong" },
  { gameId: 3, gameName: "EA FC Mobile (Direct Top-Up)" },
  { gameId: 4, gameName: "Xbox Game Pass" },
  { gameId: 5, gameName: "Tinder" },
  { gameId: 6, gameName: "Yalla Ludo" },
  { gameId: 7, gameName: "Teen Patti Gold" },
  { gameId: 8, gameName: "Farming Simulator 22" },
  { gameId: 9, gameName: "Candy Crush" },
  { gameId: 10, gameName: "Cricket Gangsta" },
  { gameId: 11, gameName: "World of Tanks" },
  { gameId: 12, gameName: "MEGA MAN X DiVE Offline" },
  { gameId: 13, gameName: "Farming Simulator 19" },
  { gameId: 14, gameName: "Roblox" },
  { gameId: 15, gameName: "VALORANT (PROMO)" },
  { gameId: 16, gameName: "Garena Free Fire MAX PINs" },
  { gameId: 17, gameName: "Nintendo eShop" },
  { gameId: 18, gameName: "Arena Breakout (PINs)" },
  { gameId: 19, gameName: "League of Legends (LOL) - Riot" },
  { gameId: 20, gameName: "Monster Hunter Rise" },
  { gameId: 21, gameName: "Hello Yo (PINs)" },
  { gameId: 22, gameName: "Lost EgameIdolons" },
  { gameId: 23, gameName: "Are You Smarter Than A 5th Grader?" },
  { gameId: 24, gameName: "Hulu" },
  { gameId: 25, gameName: "Spotify" },
  { gameId: 26, gameName: "IMO" },
  { gameId: 27, gameName: "NEW STATE MOBILE (NC)" },
  { gameId: 28, gameName: "Infinite Cultivation" },
  { gameId: 29, gameName: "T3 Arena" },
  { gameId: 30, gameName: "Yalla Live" },
  { gameId: 31, gameName: "Tango" },
  { gameId: 32, gameName: "Flash Party" },
  { gameId: 33, gameName: "Mirage: Perfect Skyline" },
  { gameId: 34, gameName: "Razer Gold PIN (IN)" },
  { gameId: 35, gameName: "Ragnarok M Eternal Love" },
  { gameId: 36, gameName: "THX Spatial Audio" },
  { gameId: 37, gameName: "Boomz" },
  { gameId: 38, gameName: "Hello Yo" },
  { gameId: 39, gameName: "GamersGate Game Store" },
  { gameId: 40, gameName: "War Thunder" },
  { gameId: 41, gameName: "Crown Four Kingdoms" },
  { gameId: 42, gameName: "Pagan Online" },
  { gameId: 43, gameName: "Indiegala Game Store" },
  { gameId: 44, gameName: "SMITE" },
  { gameId: 45, gameName: "Star Conflict" },
  { gameId: 46, gameName: "RIFT" },
  { gameId: 47, gameName: "ArcheAge" },
  { gameId: 48, gameName: "Wo Niu Card / 蜗牛一卡通 (CN)" },
  { gameId: 49, gameName: "CrossFire" },
  { gameId: 50, gameName: "BlackShot - Vertigo Games (Global)" },
  { gameId: 51, gameName: "Talion Online" },
  { gameId: 52, gameName: "Stunt Kite Party" },
  { gameId: 53, gameName: "Townsmen VR" },
  { gameId: 54, gameName: "Soul Land Reloaded" },
  { gameId: 55, gameName: "Asphalt 9" },
  { gameId: 56, gameName: "Youstar" },
  { gameId: 57, gameName: "GRIP: Combat Racing" },
  { gameId: 58, gameName: "Boxing Star" },
  { gameId: 59, gameName: "XBOX LIVE (USA)" },
  { gameId: 60, gameName: "UNCHARTED™: LEGACY OF THIEVES COLLECTION" },
  { gameId: 61, gameName: "Elden Ring" },
  { gameId: 62, gameName: "Mobile Legends" },
  { gameId: 63, gameName: "Honor Of Kings" },
  { gameId: 64, gameName: "Free Fire" },
  { gameId: 65, gameName: "Free Fire Max" },
  { gameId: 66, gameName: "Valorant" },
  { gameId: 67, gameName: "Marvel Rivals" },
  { gameId: 68, gameName: "Honkai Star Rail" },
  { gameId: 69, gameName: "Genshin Impact" },
  { gameId: 70, gameName: "Zenless Zone Zero" },
  { gameId: 71, gameName: "PUBG Mobile" },
  { gameId: 72, gameName: "Moonlight Blade M" },
  { gameId: 73, gameName: "Arena Breakout" },
  { gameId: 74, gameName: "Harry Potter: Magic Awakened" },
  { gameId: 75, gameName: "Eggy Party" },
  { gameId: 76, gameName: "Arena Of Valor" },
  { gameId: 77, gameName: "Garena Undawn" },
  { gameId: 78, gameName: "Metal Slug: Awakening" },
  { gameId: 79, gameName: "Black Clover Mobile" },
  { gameId: 80, gameName: "Blood Strike" },
  { gameId: 81, gameName: "Legends of Runeterra" },
  { gameId: 82, gameName: "EA SPORTS FC Mobile" },
  { gameId: 83, gameName: "MapleStory R" },
  { gameId: 84, gameName: "Teamfight Tactics Mobile" },
  { gameId: 85, gameName: "Point Blank" },
  { gameId: 86, gameName: "Call Of Duty Mobile" },
  { gameId: 87, gameName: "Tower of Fantasy" },
  { gameId: 88, gameName: "Brawl Stars" },
  { gameId: 89, gameName: "Clash Of Clans" },
  { gameId: 90, gameName: "League of Legends Wild Rift" },
  { gameId: 91, gameName: "League Of Legends PC" },
  { gameId: 92, gameName: "Lords Mobile" },
  { gameId: 93, gameName: "Sausage Man" },
  { gameId: 94, gameName: "Au2 Mobile" },
  { gameId: 95, gameName: "Eternal City" },
  { gameId: 96, gameName: "Laplace M" },
  { gameId: 97, gameName: "MLBB" },
  { gameId: 98, gameName: "Lifeafter" },
  { gameId: 99, gameName: "Marvel Super War" },
  { gameId: 100, gameName: "Tom And Jerry: Chase" },
  { gameId: 101, gameName: "One Punch Man Strongest" },
  { gameId: 102, gameName: "Ragnarok Retro" },
  { gameId: 103, gameName: "Ragnarok X" },
  { gameId: 104, gameName: "Ragnarok Forever Love" },
  { gameId: 105, gameName: "Ragnarok M: Eternal Love" },
  { gameId: 106, gameName: "Ragnarok Origin Global" },
  { gameId: 107, gameName: "Ragnarok Origin Global Package" },
  { gameId: 108, gameName: "Goddess of Victory: Nikke" },
  { gameId: 109, gameName: "Dragon Raja: Sea" },
  { gameId: 110, gameName: "Scroll of Onmyoji: Sakura and Sword" },
  { gameId: 111, gameName: "HATSUNE MIKU: COLORFUL STAGE" },
  { gameId: 112, gameName: "gameIdentity V" },
  { gameId: 113, gameName: "Ace Racer" },
  { gameId: 114, gameName: "Revelation Mobile" },
  { gameId: 115, gameName: "Ensemble Stars Music" },
  { gameId: 116, gameName: "Life Makeover" },
  { gameId: 117, gameName: "Dunk City Dynasty" },
  { gameId: 118, gameName: "Seal M SEA" },
  { gameId: 119, gameName: "Super Sus" },
  { gameId: 120, gameName: "Astral Guardians: Cyber Fantasy" },
  { gameId: 121, gameName: "AFK Journey" },
  { gameId: 122, gameName: "Age of Empires Mobile" },
  { gameId: 123, gameName: "Age Of Magic" },
  { gameId: 124, gameName: "Airplane Chefs" },
  { gameId: 125, gameName: "Alchemy Stars" },
  { gameId: 126, gameName: "Among Heroes: Fantasy Samkok" },
  { gameId: 127, gameName: "Apex Legends Mobile" },
  { gameId: 128, gameName: "Arena Breakout Infinite - PC" },
  { gameId: 129, gameName: "Astral Guardians: Cyber Fantasy" },
  { gameId: 130, gameName: "Astra: Knights of Veda" },
  { gameId: 131, gameName: "Be The King" },
  { gameId: 132, gameName: "Bleach Mobile 3D" },
  { gameId: 133, gameName: "Call Of Duty: Warzone Mobile" },
  { gameId: 134, gameName: "Captain Tsubasa: Ace" },
  { gameId: 135, gameName: "Chimmerland" },
  { gameId: 136, gameName: "City of Crime: Gang Wars" },
  { gameId: 137, gameName: "Clash Royale" },
  { gameId: 138, gameName: "Cloud Song" },
  { gameId: 139, gameName: "ColorBANG" },
  { gameId: 140, gameName: "Command And Conquer: Legions" },
  { gameId: 141, gameName: "Counter: SgameIde" },
  { gameId: 142, gameName: "Delta Force - Non Garena" },
  { gameId: 143, gameName: "Dead by Daylight Mobile" },
  { gameId: 144, gameName: "Devil May Cry: Peak of Combat" },
  { gameId: 145, gameName: "Draconia Saga" },
  { gameId: 146, gameName: "Dragon Nest 2 Evolution" },
  { gameId: 147, gameName: "Dragon Pow!" },
  { gameId: 148, gameName: "Dragonheir Silent Gods" },
  { gameId: 149, gameName: "Dunk City Dynasty" },
  { gameId: 150, gameName: "Dynasty Warriors Overlords" },
  { gameId: 151, gameName: "EVE Echoes" },
  { gameId: 152, gameName: "Echocalypse" },
  { gameId: 153, gameName: "Era of Celestials" },
  { gameId: 154, gameName: "EOS RED" },
  { gameId: 155, gameName: "FF Global" },
  { gameId: 156, gameName: "Farlight 84" },
  { gameId: 157, gameName: "Football Master 2" },
  { gameId: 158, gameName: "Growtopia" },
  { gameId: 159, gameName: "Guns of Glory" },
  { gameId: 160, gameName: "Hay Day" },
  { gameId: 161, gameName: "Honkai Impact 3" },
  { gameId: 162, gameName: "Hustle Castle: Medieval Games" },
  { gameId: 163, gameName: "Hyper Front Sea" },
  { gameId: 164, gameName: "gameIdle Legends: GODS SAGA" },
  { gameId: 165, gameName: "Immortal Awakening" },
  { gameId: 166, gameName: "Indus Battle Royale" },
  { gameId: 167, gameName: "Jawaker Token" },
  { gameId: 168, gameName: "Jade Dynasty: New Fantasy" },
  { gameId: 169, gameName: "Jade Legends" },
  { gameId: 170, gameName: "Kings Choice" },
  { gameId: 171, gameName: "Knives Out" },
  { gameId: 172, gameName: "LDCloud" },
  { gameId: 173, gameName: "Legend of Mushroom: Rush" },
  { gameId: 174, gameName: "Light of Thel: New Era" },
  { gameId: 175, gameName: "Love And Deepspace" },
  { gameId: 176, gameName: "Lovebrush Chronicles" },
  { gameId: 177, gameName: "Ludo Club" },
  { gameId: 178, gameName: "Luna Online New World" },
  { gameId: 179, gameName: "Magic Chess: Go Go" },
  { gameId: 180, gameName: "MapleStory M" },
  { gameId: 181, gameName: "Marvel Snap" },
  { gameId: 182, gameName: "Mirage Perfect Skyline" },
  { gameId: 183, gameName: "Modern Strike Online" },
  { gameId: 184, gameName: "Monster Saga: Evolution" },
  { gameId: 185, gameName: "MOB RUSH" },
  { gameId: 186, gameName: "Mythic Samkok - Link Razer" },
  { gameId: 187, gameName: "NBA INFINITE" },
  { gameId: 188, gameName: "Never After" },
  { gameId: 189, gameName: "Night Crows - Drop Link" },
  { gameId: 190, gameName: "Naruto Slugfest" },
  { gameId: 191, gameName: "OCTOPATH TRAVELER CotC" },
  { gameId: 192, gameName: "Omega Legends" },
  { gameId: 193, gameName: "One Punch Man World - In App Pack" },
  { gameId: 194, gameName: "Pixel Gun 3D" },
  { gameId: 195, gameName: "Pixel Starships" },
  { gameId: 196, gameName: "Pokémon Unite" },
  { gameId: 197, gameName: "Punishing Gray Raven" },
  { gameId: 198, gameName: "PUBG Mobile Lite" },
  { gameId: 199, gameName: "PUBG New State Mobile" },
  { gameId: 200, gameName: "Ragnarok M Classic Zeny Only" },
  { gameId: 201, gameName: "Ragnarok V: Returns" },
  { gameId: 202, gameName: "Return of Condor Heroes" },
  { gameId: 203, gameName: "Rhythm Hive" },
  { gameId: 204, gameName: "Rise of Kingdoms" },
  { gameId: 205, gameName: "Saint Seiya Awakening" },
  { gameId: 206, gameName: "Seal M SEA" },
  { gameId: 207, gameName: "Sky Children of the Light" },
  { gameId: 208, gameName: "Snowbreak: Containment Zone" },
  { gameId: 209, gameName: "SOULS" },
  { gameId: 210, gameName: "Solo Leveling: Arise - Drop Link" },
  { gameId: 211, gameName: "Soul Land: New World" },
  { gameId: 212, gameName: "Speed Drifters" },
  { gameId: 213, gameName: "Stumble Guys" },
  { gameId: 214, gameName: "Super Mecha Champions" },
  { gameId: 215, gameName: "Super Sus" },
  { gameId: 216, gameName: "Tarisland - Drop Link" },
  { gameId: 217, gameName: "Tarisland Via gameId" },
  { gameId: 218, gameName: "The Ants" },
  { gameId: 219, gameName: "The Legend of Neverland" },
  { gameId: 220, gameName: "Tower Brawl" },
  { gameId: 221, gameName: "TSX by Astronize" },
  { gameId: 222, gameName: "Undawn Global" },
  { gameId: 223, gameName: "Whiteout Survival" },
  { gameId: 224, gameName: "Wuthering Waves Via Login" },
  { gameId: 225, gameName: "YS 6 Mobile" },
  { gameId: 226, gameName: "Yalla Ludo Diamonds" },
  { gameId: 227, gameName: "Zepeto" },
  { gameId: 228, gameName: "Tower of Fantasy" },
  { gameId: 229, gameName: "Eternal City" },
  { gameId: 230, gameName: "Laplace M" },
  { gameId: 231, gameName: "Life Makeover" },
];

async function main() {
  console.log("Starting to seed database...");

  const games = await prisma.Game.createMany({
    data: gamesList,
    skipDuplicates: true,
  });

  console.log(`Seeded ${games.count} games successfully!`);
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
